# Generated by Django 4.1.1 on 2022-11-04 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Java',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('book', models.CharField(max_length=30)),
                ('rate', models.FloatField()),
                ('year', models.IntegerField()),
                ('language', models.CharField(max_length=35)),
            ],
        ),
        migrations.CreateModel(
            name='Python',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('no', models.IntegerField()),
                ('name', models.CharField(max_length=30)),
                ('book', models.CharField(max_length=30)),
                ('rate', models.FloatField()),
                ('year', models.IntegerField()),
                ('language', models.CharField(max_length=35)),
            ],
        ),
    ]
