# Generated by Django 4.1.1 on 2022-11-05 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_detail1model_delete_detailmodel'),
    ]

    operations = [
        migrations.DeleteModel(
            name='UserModel',
        ),
    ]
