# Generated by Django 4.1.1 on 2022-10-03 16:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HyderabadJobs',
            new_name='Bjob',
        ),
        migrations.RenameModel(
            old_name='BangaloreJobs',
            new_name='Hjob',
        ),
        migrations.RenameModel(
            old_name='PuneJobs',
            new_name='Pjob',
        ),
    ]
